# Cloud Build Trigger configuration for SvelteKit -> Cloud Run deployment
#
# This trigger references the repo's build config at `app/cloudbuild.yaml`.
# Replace placeholders (REPO_OWNER, REPO_NAME, SERVICE_ACCOUNT_EMAIL) before importing,
# or pass substitutions when creating the trigger with gcloud.
#
# Supported creation methods (examples below):
# 1) Import this trigger YAML directly into Cloud Build:
#    gcloud alpha builds triggers import --source=app/cloudbuild-trigger/trigger.yaml
#
# 2) Create a GitHub-backed trigger (via gcloud) that references the same build config:
#    gcloud beta builds triggers create github \
#      --name="sveltekit-deploy-trigger" \
#      --repo-owner="REPO_OWNER" \
#      --repo-name="REPO_NAME" \
#      --branch-pattern="^main$" \
#      --build-config="app/cloudbuild.yaml" \
#      --substitutions=_SERVICE="sveltekit-app",_REGION="us-central1",_SERVICE_ACCOUNT="SERVICE_ACCOUNT_EMAIL"
#
# 3) Create a Cloud Source Repo trigger:
#    gcloud beta builds triggers create cloud-source-repositories \
#      --name="sveltekit-deploy-trigger" \
#      --repo="REPO_NAME" \
#      --branch-pattern="^main$" \
#      --build-config="app/cloudbuild.yaml" \
#      --substitutions=_SERVICE="sveltekit-app",_REGION="us-central1",_SERVICE_ACCOUNT="SERVICE_ACCOUNT_EMAIL"
#
# IAM / Permissions required for automatic deploy from Cloud Build:
# - Enable APIs: Cloud Build, Cloud Run, Container Registry (or Artifact Registry)
#     gcloud services enable cloudbuild.googleapis.com run.googleapis.com containerregistry.googleapis.com
#
# - Give Cloud Build service account permission to deploy to Cloud Run:
#   Replace PROJECT_ID and PROJECT_NUMBER appropriately.
#
#   # 1) Grant Cloud Build SA the ability to administer Cloud Run
#   gcloud projects add-iam-policy-binding PROJECT_ID \
#     --member="serviceAccount:PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
#     --role="roles/run.admin"
#
#   # 2) Allow Cloud Build SA to push images to Container Registry (if using Container Registry)
#   gcloud projects add-iam-policy-binding PROJECT_ID \
#     --member="serviceAccount:PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
#     --role="roles/storage.admin"
#
#   # 3) If you plan for Cloud Build to deploy using a specific runtime/service account
#   #    (the account used by your Cloud Run service), grant Cloud Build SA iam.serviceAccountUser on that account:
#   gcloud iam service-accounts add-iam-policy-binding SERVICE_ACCOUNT_EMAIL \
#     --member="serviceAccount:PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
#     --role="roles/iam.serviceAccountUser"
#
# Notes:
# - Prefer attaching a dedicated service account to Cloud Run (via --service-account) with the minimum
#   roles needed to access Firebase (Firestore, Storage, etc.). Do not put service account JSON in the repo.
# - `app/cloudbuild.yaml` (referenced by this trigger) already contains build/test/push/deploy steps.
# - Pass a non-empty `_SERVICE_ACCOUNT` substitution if you want Cloud Build to deploy Cloud Run with a specific SA.
#
# Example usage to import this trigger and set substitutions from the command line:
# gcloud alpha builds triggers import --source=app/cloudbuild-trigger/trigger.yaml \
#   --project=PROJECT_ID
#
# Example to create trigger via import then update substitutions using API/UI:
# - After import, open Google Cloud Console > Cloud Build > Triggers and edit the trigger to set:
#   Substitutions: _SERVICE=sveltekit-app, _REGION=us-central1, _SERVICE_ACCOUNT=SERVICE_ACCOUNT_EMAIL
#
# ------ Trigger YAML below ------
#
name: "sveltekit-deploy-trigger"
description: "Trigger that runs app/cloudbuild.yaml to build, test, push, and deploy the SvelteKit app to Cloud Run"
# Set to false to temporarily disable the trigger
disabled: false

# GitHub configuration (use either github or triggerTemplate/cloud-source-repositories depending on your repo)
# Replace REPO_OWNER and REPO_NAME with your GitHub repo owner/name.
github:
  owner: "REPO_OWNER"    # e.g. your GitHub username or organization
  name: "REPO_NAME"      # e.g. repository name
  push:
    # Regex branch pattern (trigger on pushes to main). Modify as needed.
    branch: "^main$"

# If you prefer Cloud Source Repositories instead of GitHub, comment out the github block above
# and uncomment the triggerTemplate block below and set repoName to your CSR repo name.
#
# triggerTemplate:
#   projectId: "PROJECT_ID"
#   repoName: "REPO_NAME"
#   branchName: "^main$"

# Path to the build config file inside the repository
filename: "app/cloudbuild.yaml"

# Default substitutions (override in Cloud Console or via gcloud when creating the trigger)
substitutions:
  _SERVICE: "sveltekit-app"
  _REGION: "us-central1"
  _SERVICE_ACCOUNT: ""   # optional: service account email to attach to Cloud Run; leave empty to use default

# Optional: only run the trigger when changes affect files under `app/` (helps reduce builds)
includedFiles:
  - "app/**"
ignoredFiles:
  - "README.md"
  - "docs/**"
