# Cloud Build config to build a Docker image for the SvelteKit app, push it to Container Registry,
# and deploy the image to Cloud Run (managed).
#
# How to trigger from CI / locally (exact commands):
# 1) Run Cloud Build and pass substitutions (replace PROJECT_ID, SERVICE_NAME, REGION as needed):
#    gcloud builds submit --config app/cloudbuild.yaml --substitutions=_SERVICE=\"sveltekit-app\",_REGION=\"us-central1\"
#
# 2) Alternatively, to trigger and set a specific tag:
#    gcloud builds submit --config app/cloudbuild.yaml --substitutions=_SERVICE=\"sveltekit-app\",_REGION=\"us-central1\",COMMIT_SHA=\"my-tag\"
#
# After the build completes, you can also manually deploy (example):
#    gcloud run deploy sveltekit-app \
#      --image gcr.io/PROJECT_ID/sveltekit-app:COMMIT_SHA \
#      --region us-central1 \
#      --platform managed \
#      --allow-unauthenticated
#
# Notes:
# - This file uses the built-in substitution $PROJECT_ID and $COMMIT_SHA.
# - You can override the user-defined substitutions `_SERVICE` and `_REGION` at build time.
# - To attach a service account to the Cloud Run service, add:
#      --service-account=SERVICE_ACCOUNT_EMAIL
#   to the gcloud run deploy args (recommended for accessing Firebase Admin APIs).
#
# Security reminder:
# - Do NOT store service account JSON inside the repository. Use Workload Identity / attach a service account, or use Secret Manager.

substitutions:
  # Default values; override when triggering the build if needed.
  _SERVICE: 'sveltekit-app'
  _REGION: 'us-central1'
  _SERVICE_ACCOUNT: ''

# Set logging option required when a build.service_account is specified.
# Cloud Build requires either a logs bucket or one of the logging options when a custom service account is used.
options:
  logging: CLOUD_LOGGING_ONLY

# Ensure the built image is registered as an output artifact so Cloud Build will push it.
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE}:${COMMIT_SHA}'

steps:
  # Run tests before building. Uses Node 22 image to install deps and run your test suite.
  # matrix-js-sdk requires Node >= 22, so use node:22 here.
  - name: 'node:22'
    id: 'Run tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "Running tests with Node 22..."
        npm ci
        npm test

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE}:${COMMIT_SHA}'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE}:${COMMIT_SHA}'

  # Deploy the pushed image to Cloud Run (managed). Optionally attach a service account if provided.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail

        # Optional: print context for debugging
        echo "Project: $PROJECT_ID"
        echo "Service: ${_SERVICE}"
        echo "Region: ${_REGION}"
        echo "Image: gcr.io/$PROJECT_ID/${_SERVICE}:${COMMIT_SHA}"
        echo "Service account: ${_SERVICE_ACCOUNT:-<none>}"

        # Prepare optional service account argument if provided
        if [ -n "${_SERVICE_ACCOUNT:-}" ]; then
          SERVICE_ACCOUNT_ARG="--service-account=${_SERVICE_ACCOUNT}"
        else
          SERVICE_ACCOUNT_ARG=""
        fi

        # Deploy to Cloud Run (allow unauthenticated by default; remove flag for private services)
        gcloud run deploy "${_SERVICE}" \
          --image="gcr.io/$PROJECT_ID/${_SERVICE}:${COMMIT_SHA}" \
          --region="${_REGION}" \
          --platform=managed \
          $$SERVICE_ACCOUNT_ARG \
          --allow-unauthenticated \
          --quiet

# Optional timeout (increase if build + deploy may take longer than default)
timeout: '1200s'
